language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

addons:
  apt:
    sources:
    - sourceline: 'deb [ arch=amd64 ] https://downloads.skewed.de/apt bionic main'
      key_url: 'http://ha.pool.sks-keyservers.net/pks/lookup?op=get&search=0x612DEFB798507F25'
    # TODO: remove the below once we drop python 2.7.
    - ubuntu-toolchain-r-test
    packages:
    - python3-graph-tool
    - libqt5gui5  # pyqt5>5.11 fails to load the xcb platform plugin without it

install:
  - pip install --upgrade pip setuptools wheel  # install with latest tools
  - pip install --upgrade --upgrade-strategy eager .[dev]  # get latest deps

before_script:
  # As graph-tool cannot be installed by pip, link to the system installation
  # from the virtual environment.
  - ln -s "/usr/lib/python3/dist-packages/graph_tool" $(python -c "import site; print(site.getsitepackages()[0])")

script:
# - make lint
  - make test
  - make doc

after_success:
  - coveralls
